# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb006b3335c0b02bec11ab03a67d48f255239febccc525f6aa7052b14d3cc7d282c027287b916f72ec6976dfe9000e5b8218bc8e5601724da1b47c1ce1d75c0f

test:
  secret_key_base: 3d0cd37277b836dd9dcec9d0819e85d3ae2f4358bb77a9ca9469d420fd6bc9e6d4cb65ef52f935b421ee8f1d0b0db8aa72e8e99be7276ce7dbf121edd676c65c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
